### ISSUE TITLE
No Textures Glitch

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#12]
No textures been loading, how to even add USD file textures??

![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/db1c0c19-5ae4-40c4-a994-e34d3eda5eb5)

**Comment by Fyoncle** [comment]
Image textures just dont apply at all into the map, its just a white material with no nodes.

**Comment by Fyoncle** [comment]
> Hi! MiEx by default uses MaterialX for the materials (which comes with USD by default). It uses this in order to be able to support biome colours and animated textures. Unfortunately, Blender does not support MaterialX. In the latest release ( https://github.com/BramStoutProductions/MiEx/releases/tag/v1.2.2 ) MiEx now comes with an extra resource pack called `UsdPreviewSurface`. If you enable that, MiEx will create UsdPreviewSurface materials instead of MaterialX materials. Blender can import UsdPreviewSurface.
> 
> Unfortunately, UsdPreviewSurface doesn't allow me to handle biome colours or animated textures, so you'd have to fix the materials after importing. The biome colours are still available as vertex colours, which you can access with the Color Attribute node. You'd want the `Cd` color attribute. You multiply this with the texture in order to get the tinted version. Animating the textures is more difficult. You'd need to scale up the UVs so that it only shows a single frame and then animate the offset using an expression.
> 
> Please let me know if the latest version using the `UsdPreviewSurface` resource pack enabled works better!

About virus things browsers saying, is this a false flag?

**Comment by BramStout** [comment]
It is indeed a false flag. I don't really know what's triggering it. I'm not getting it myself.

**Comment by Fyoncle** [comment]
> It is indeed a false flag. I don't really know what's triggering it. I'm not getting it myself.

Also after using MiEx my computer just slowed down, with ranging from 2 minutes to 4 minutes, weird freezes happening in my computer and more, is this normal?

**Comment by BramStout** [comment]
It's normal for it to slow down your computer while you're actively using it, because MiEx uses many cores to speed up loading worlds and exporting worlds. But it should not slow down your computer after MiEx has been closed! The only thing that I can think of is maybe anti-virus going through the USD files that it created or the base_resource_pack files which it extracts from your Minecraft install. Those can be quite a lot of files, which could maybe take a bit for your anti-virus to check. But the anti-virus shouldn't be checking all of that anyways, so I'm not sure what's exactly going on.

But I'm not getting any of that myself (I am using Windows Defender), so it would be difficult for me to reproduce this slowing down. Could you check in Task Manager which processes are using up a lot of your CPU and Disk?

**Comment by Fyoncle** [comment]
> It's normal for it to slow down your computer while you're actively using it, because MiEx uses many cores to speed up loading worlds and exporting worlds. But it should not slow down your computer after MiEx has been closed! The only thing that I can think of is maybe anti-virus going through the USD files that it created or the base_resource_pack files which it extracts from your Minecraft install. Those can be quite a lot of files, which could maybe take a bit for your anti-virus to check. But the anti-virus shouldn't be checking all of that anyways, so I'm not sure what's exactly going on.
> 
> But I'm not getting any of that myself (I am using Windows Defender), so it would be difficult for me to reproduce this slowing down. Could you check in Task Manager which processes are using up a lot of your CPU and Disk?

No process using my CPU except Discord and Chrome.
