### ISSUE TITLE
Fullscreen Bug

### ISSUE THREAD

**Issue by Aspirata** [BramStoutProductions/MiEx#17]
When i use MiEx in fullscreen this happens

https://github.com/BramStoutProductions/MiEx/assets/102383379/294bd913-5e3f-4f09-8818-40eed27e1544

**Comment by Aspirata** [comment]
I also can't see anything in my worlds

**Comment by BramStout** [comment]
That's very weird. Next to the MiEx.jar file, there should be a log.txt file. Could you share that file? Hopefully that will tell us more about what's going on

**Comment by Aspirata** [comment]
it got fixed somehow, but another error occurred
[log.txt](https://github.com/BramStoutProductions/MiEx/files/15107476/log.txt)

**Comment by BramStout** [comment]
> it got fixed somehow, but another error occurred [log.txt](https://github.com/BramStoutProductions/MiEx/files/15107476/log.txt)

It looks like it wasn't able to find a Minecraft Java Edition install that has valid Minecraft versions installed. This caused it to not be able to automatically extract the base resource pack from Minecraft. If you're using the vanilla launcher, all you should have to do is launch the latest version of the game and it will download the latest version. Then you can launch MiEx again and it should be able to automatically extract the base resource pack from that latest version of Minecraft.

You can also manually create the base resource pack. You can find more info about that [here.](https://github.com/BramStoutProductions/MiEx/issues/4#issuecomment-2075105901)

It also looks like there is a separate error when trying to load in the world where it's not able to read the chunk data from the region files. If you haven't, please try the latest version of MiEx to see if the issue is in there as well. If so, would you be able to share the world (or some other world that shows the same issue)?
