### ISSUE TITLE
Grayed Out Vegetations

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#22]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/6c6ff0f7-8d93-44a9-9fdd-98fc72849ead)
The vegetations on the world is always gray, no matter what, leaves, grass block, grass, and any other thing, is there a fix for that? because i don't wanna set them manually, also we still "IN NEED OF" the addon called Mineways to set the textures into closest, which is if there was a special addon for MiEx to have control ALL OVER OUR WORLD then it would be way better.

**Comment by michal212345** [comment]
There is no way of automatically adding colours to vegetation because Blender does not support MaterialX; this is not a problem in any other software.

**Comment by Fyoncle** [comment]
> There is no way of automatically adding colours to vegetation because Blender does not support MaterialX; this is not a problem in any other software.

Still there should be any possible way.

**Comment by BramStout** [comment]
This is an issue with Blender not fully supporting USD. MiEx by default uses MaterialX materials so that it can do biome colours, animated textures, and set the texture filter. Blender, unfortunately, does not support importing in MaterialX materials. It only supports UsdPreviewSurface materials. Therefore, MiEx provides a resource pack to specifically export out UsdPreviewSurface materials, but that doesn't support biome colours, animated textures, and setting the texture filter. This means that when importing into Blender, you still need to fix the materials after import.

If Blender's USD importer would allow us to specify Blender's native shading nodes in USD, then we could create material templates that use these nodes and the materials in Blender would then be set up correctly and just work. Unfortunately, that's not the case.

This could be fixed using an addon. The addon could potentially hook into the USD importer and fix materials immediately in there. Or, the addon could fix materials after the fact. This is something that I will be looking into, but I don't use Blender myself and I don't know much about how it works, so I can't say anything about when that will be done. Maybe somebody else, who knows a lot more about Blender addons, could make it and send it in as a pull request so that everyone can use it.

**Comment by Fyoncle** [comment]
> This is an issue with Blender not fully supporting USD. MiEx by default uses MaterialX materials so that it can do biome colours, animated textures, and set the texture filter. Blender, unfortunately, does not support importing in MaterialX materials. It only supports UsdPreviewSurface materials. Therefore, MiEx provides a resource pack to specifically export out UsdPreviewSurface materials, but that doesn't support biome colours, animated textures, and setting the texture filter. This means that when importing into Blender, you still need to fix the materials after import.
> 
> If Blender's USD importer would allow us to specify Blender's native shading nodes in USD, then we could create material templates that use these nodes and the materials in Blender would then be set up correctly and just work. Unfortunately, that's not the case.
> 
> This could be fixed using an addon. The addon could potentially hook into the USD importer and fix materials immediately in there. Or, the addon could fix materials after the fact. This is something that I will be looking into, but I don't use Blender myself and I don't know much about how it works, so I can't say anything about when that will be done. Maybe somebody else, who knows a lot more about Blender addons, could make it and send it in as a pull request so that everyone can use it.

![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/3643b55f-de70-40cd-9c17-e94269c76fe7)
Wont this work? someone typed that 4 years ago.

**Comment by BramStout** [comment]
> > This is an issue with Blender not fully supporting USD. MiEx by default uses MaterialX materials so that it can do biome colours, animated textures, and set the texture filter. Blender, unfortunately, does not support importing in MaterialX materials. It only supports UsdPreviewSurface materials. Therefore, MiEx provides a resource pack to specifically export out UsdPreviewSurface materials, but that doesn't support biome colours, animated textures, and setting the texture filter. This means that when importing into Blender, you still need to fix the materials after import.
> > If Blender's USD importer would allow us to specify Blender's native shading nodes in USD, then we could create material templates that use these nodes and the materials in Blender would then be set up correctly and just work. Unfortunately, that's not the case.
> > This could be fixed using an addon. The addon could potentially hook into the USD importer and fix materials immediately in there. Or, the addon could fix materials after the fact. This is something that I will be looking into, but I don't use Blender myself and I don't know much about how it works, so I can't say anything about when that will be done. Maybe somebody else, who knows a lot more about Blender addons, could make it and send it in as a pull request so that everyone can use it.
> 
> ![image](https://private-user-images.githubusercontent.com/63975256/325360542-3643b55f-de70-40cd-9c17-e94269c76fe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODg3MDAsIm5iZiI6MTcxMzk4ODQwMCwicGF0aCI6Ii82Mzk3NTI1Ni8zMjUzNjA1NDItMzY0M2I1NWYtZGU3MC00MGNkLTljMTctZTk0MjY5Yzc2ZmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE5NTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYmM3ZjMyZWMwZDk3NjFiOTEzNmQ2NWZjMjNkMjJhNTAyNzExNWEwOTQ2OGU0ZWQ1ZDQ0MzdlZDllZGEwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JAAOx7QwRU-rgOX_tpEalMK1D3IdKkHbrcBYOX5GGDs) Wont this work? someone typed that 4 years ago.

This appears to talk about importing and exporting mtlx files, which is where each material is written out into it's own file with an .mtlx extension. MiEx exports out materials as USD data and not mltx data. Both allow you to specify MaterialX materials, just in different file types. MiEx uses USD data because USD data can also store other kinds of materials.

As far as I know, there currently just isn't a way to import USD files with perfect materials. This can be fixed using an addon that can encode and decode Blender's shading nodes as USD data, but I don't think that addon exists yet. However, I do believe that at some point somebody will make it, or that a new version of Blender will natively support it.
