### ISSUE TITLE
The White Grass Models

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#35]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/8b88ce22-7704-4077-ab84-824133ffc89e)
These just getting added in the snowy biomes but they clip inside the blocks  and dont be shown unless i scale them, any fix possible?
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/9eb3c994-1849-49a6-995f-66738bdfdbaf)
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/23a750ee-d7ef-4101-9daa-2ef03b42311b)
They actually here but not possible to see
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/19158ed4-ea0c-4646-a3de-93fcc5e2a92d)
If i scale it, then we can see it, it's because they are clippign to the grass because they are literally the same size.

**Comment by BramStout** [comment]
While the block state and block model files tell MiEx a lot about how to export certain blocks, they don't tell MiEx everything. Like whether it should be seen as a transparent block, should have biome colours, should have a random offset, should be waterlogged by default, etc. For this, MiEx has the `miex_config.json` file where you can give MiEx this information. This can be a tedious thing, since there is unfortunately no automated way to do this, since these things aren't specified anywhere except for the source code of Minecraft or the mods (which we don't have access to).

What I'd recommend is to create a file called `miex_config.json` in the resource pack that you created for the modpack. Then, in there you can tell MiEx about the modded blocks. You can read more about how the `miex_config.json` file works here: https://github.com/BramStoutProductions/MiEx/wiki/3.-Pipeline-Integration-and-Customisations#configurations

Here is an example `miex_config.json` file that adds a bunch of Regions Unexplored blocks to the various biome colours:
```JSON
{
    "leavesOcclusion.add": [ "regions_unexplored:willow_leaves", "regions_unexplored:white_magnolia_leaves",
                            "regions_unexplored:socotra_leaves", "regions_unexplored:small_oak_leaves",
                            "regions_unexplored:silver_birch_leaves", "regions_unexplored:redwood_leaves",
                            "regions_unexplored:red_maple_leaves", "regions_unexplored:pink_magnolia_leaves",
                            "regions_unexplored:pine_leaves", "regions_unexplored:palm_leaves",
                            "regions_unexplored:orange_maple_leaves", "regions_unexplored:mauve_leaves",
                            "regions_unexplored:maple_leaves", "regions_unexplored:magnolia_leaves",
                            "regions_unexplored:larch_leaves", "regions_unexplored:kapok_leaves",
                            "regions_unexplored:joshua_leaves", "regions_unexplored:golden_larch_leaves",
                            "regions_unexplored:flowering_leaves", "regions_unexplored:eucalyptus_leaves",
                            "regions_unexplored:enchanted_birch_leaves", "regions_unexplored:dead_pine_leaves",
                            "regions_unexplored:dead_leaves", "regions_unexplored:cypress_leaves",
                            "regions_unexplored:brimwood_leaves", "regions_unexplored:blue_magnolia_leaves",
                            "regions_unexplored:blackwood_leaves", "regions_unexplored:baobab_leaves",
                            "regions_unexplored:bamboo_log_leaves", "regions_unexplored:bamboo_leaves",
                            "regions_unexplored:ashen_leaves", "regions_unexplored:apple_oak_leaves",
                            "regions_unexplored:alpha_leaves"],
    "grassColormapBlocks.add": [
        "regions_unexplored:bladed_grass", "regions_unexplored:bladed_tall_grass", "regions_unexplored:clover", "regions_unexplored:elephant_ear_plant",
        "regions_unexplored:kapok_vines", "regions_unexplored:maple_leave_pile", "regions_unexplored:medium_grass", "regions_unexplored:ru_grass_block",
        "regions_unexplored:steppe_grass", "regions_unexplored:steppe_tall_grass"
    ],
    "foliageColormapBlocks.add": [
        "regions_unexplored:apple_oak_leaves", "regions_unexplored:bamboo_log_leaves", "regions_unexplored:cypress_leaves",
        "regions_unexplored:enchanted_birch_leaves", "regions_unexplored:eucalyptus_leaves", "regions_unexplored:joshua_leaves",
        "regions_unexplored:kapok_leaves", "regions_unexplored:magnolia_leaves", "regions_unexplored:maple_leaves",
        "regions_unexplored:orange_maple_leaves", "regions_unexplored:palm_leaves", "regions_unexplored:pine_leaves",
        "regions_unexplored:red_maple_leaves", "regions_unexplored:redwood_leaves", "regions_unexplored:silver_birch_leaves",
        "regions_unexplored:socotra_leaves", "regions_unexplored:small_oak_leaves", "regions_unexplored:white_magnolia_leaves",
        "regions_unexplored:willow_leaves"
    ],
    "doubleSided.add": [
        "regions_unexplored:bladed_grass", "regions_unexplored:bladed_tall_grass", "regions_unexplored:elephant_ear_plant",
        "regions_unexplored:medium_grass", "regions_unexplored:steppe_grass", "regions_unexplored:steppe_tall_grass"
    ]
}
```
You can notice that it specified `.add` at the end. This tells MiEx to add these blocks to the list of blocks already specified in the base_resource_pack's config file, rather than override the entire list.

While it would be nice to be able to automate this, unfortunately, there isn't any automated way to figure this stuff out. So, we have to manually tell MiEx about it using these config files.
