### ISSUE TITLE
New LOD Placement System

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#36]
Current LOD Selection system completely terrible and limits me a lot, for example if i want LOD at the corners of the map instead of 1 huge cube, for example just like edges, or a similar system to world selection but with enabling "LOD Selection Mod" and holding left click and selecting lod places, or a checkbox to make the middle of LOD selection empty, but only leaves the edges, you got what i mean you know, selecting that way is kinda annoying.
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/02bb7929-b240-41e7-a0f3-d45cdf7b4619)

**Comment by BramStout** [comment]
When Level-of-Detail is enabled, the blue LOD area specifies the area that should be full resolution. The area outside of it will get lower and lower resolution the further away from the blue LOD area it is. This basically means that in pretty much any export, you only need to specify a single area (the foreground).

I agree that the controls for specifying the LOD area can be improved and that is on the to-do list. However, I would like to clarify on your suggestion to specify multiple LOD areas. Because an LOD area is the area that should have full detail, not the area that should have reduced detail. So are you asking for the ability to select multiple areas that should have full detail and that the areas in between them have reduced LOD detail?

**Comment by Fyoncle** [comment]
> When Level-of-Detail is enabled, the blue LOD area specifies the area that should be full resolution. The area outside of it will get lower and lower resolution the further away from the blue LOD area it is. This basically means that in pretty much any export, you only need to specify a single area (the foreground).
> 
> I agree that the controls for specifying the LOD area can be improved and that is on the to-do list. However, I would like to clarify on your suggestion to specify multiple LOD areas. Because an LOD area is the area that should have full detail, not the area that should have reduced detail. So are you asking for the ability to select multiple areas that should have full detail and that the areas in between them have reduced LOD detail?

Oh, then thats now different, but still i want better way to select LOD places, i dont wanna put one by one coordinates by hand.

**Comment by BramStout** [comment]
Okay. A nicer way of selecting LOD areas was on the to-do list anyways!

**Comment by Fyoncle** [comment]
Also somehow LOD kind of adding more blocks, and MORE CURSED placement, and doesnt avoid lag at all, i don't think current LOD system is efficient or works at all.

**Comment by BramStout** [comment]
The LOD isn't actually adding more blocks or providing more curved placement of blocks. The LOD system works by lowering the resolution of the world. So, it would replace a group of 2x2x2, 4x4x4, 8x8x8, or 16x16x16 blocks with one big block. But it then does need to decide on a single block to represent that entire group of blocks. This will always be an inaccurate representation of the world (which can look cursed when up close). But, the whole point is that this only happens in the far background, where you won't notice it. The main MiEx artwork uses LODs and you don't notice it, because it's only in the far background. ![Main MiEx artwork](https://bramstout.nl/content/miex_main_artwork.png)

The LOD system simplifies the world in the background, which reduces the amount of different textures used there, reduces the total amount of polygons, and the total amount of objects. All of these things provide performance improvements when dealing with very large worlds. The main benefit of it, comes when rendering with a ray tracer, though. It does help somewhat in the viewport of DCCs, but things like using atlases (which can be created using the atlas creator tool found in the bottom right of the window) can provide more significant speed ups there.

**Comment by BramStout** [comment]
The UX for specifying the LOD area has now been improved. By holding shift, you can now set and manipulate the LOD area just like you can with the export bounds. You can get the latest version here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.5.0

**Comment by Fyoncle** [comment]
> The LOD isn't actually adding more blocks or providing more curved placement of blocks. The LOD system works by lowering the resolution of the world. So, it would replace a group of 2x2x2, 4x4x4, 8x8x8, or 16x16x16 blocks with one big block. But it then does need to decide on a single block to represent that entire group of blocks. This will always be an inaccurate representation of the world (which can look cursed when up close). But, the whole point is that this only happens in the far background, where you won't notice it. The main MiEx artwork uses LODs and you don't notice it, because it's only in the far background. ![Main MiEx artwork](https://camo.githubusercontent.com/ab52ad0594ba25ea34ce06a96efcfc0a9a89f89fadbc158adaa07accb80b836b/68747470733a2f2f6272616d73746f75742e6e6c2f636f6e74656e742f6d6965785f6d61696e5f617274776f726b2e706e67)
> 
> The LOD system simplifies the world in the background, which reduces the amount of different textures used there, reduces the total amount of polygons, and the total amount of objects. All of these things provide performance improvements when dealing with very large worlds. The main benefit of it, comes when rendering with a ray tracer, though. It does help somewhat in the viewport of DCCs, but things like using atlases (which can be created using the atlas creator tool found in the bottom right of the window) can provide more significant speed ups there.

But i did use MiEx with a "kinda small" world and it really really really really really lagged in blender and freezed my computer many times, file size was almost 4 GB, how did u even render this MiEx banner??? [i used lod too, AT THE WHOLE MAP.]

**Comment by StandingPadAnimations** [comment]
> > The LOD isn't actually adding more blocks or providing more curved placement of blocks. The LOD system works by lowering the resolution of the world. So, it would replace a group of 2x2x2, 4x4x4, 8x8x8, or 16x16x16 blocks with one big block. But it then does need to decide on a single block to represent that entire group of blocks. This will always be an inaccurate representation of the world (which can look cursed when up close). But, the whole point is that this only happens in the far background, where you won't notice it. The main MiEx artwork uses LODs and you don't notice it, because it's only in the far background. ![Main MiEx artwork](https://camo.githubusercontent.com/ab52ad0594ba25ea34ce06a96efcfc0a9a89f89fadbc158adaa07accb80b836b/68747470733a2f2f6272616d73746f75742e6e6c2f636f6e74656e742f6d6965785f6d61696e5f617274776f726b2e706e67)
> > The LOD system simplifies the world in the background, which reduces the amount of different textures used there, reduces the total amount of polygons, and the total amount of objects. All of these things provide performance improvements when dealing with very large worlds. The main benefit of it, comes when rendering with a ray tracer, though. It does help somewhat in the viewport of DCCs, but things like using atlases (which can be created using the atlas creator tool found in the bottom right of the window) can provide more significant speed ups there.
> 
> But i did use MiEx with a "kinda small" world and it really really really really really lagged in blender and freezed my computer many times, file size was almost 4 GB, how did u even render this MiEx banner??? [i used lod too, AT THE WHOLE MAP.]

What's the size of the selection? I haven't had any issues with export sizes
