### ISSUE TITLE
See Through Leaf

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#39]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/2b2d398b-70c6-43e8-abbb-7570be859231)
When you enable "remove caves" it also removes modded leaf's grounds which is you can see the WHOLE world through, i remember you said something like without MaterialX you cannot tell either its a leaf or not so that algorithm also deletes under the modded leaves cuz it doesnt know its leaf

**Comment by BramStout** [comment]
MiEx by default doesn't know how to handle blocks occluding other blocks. The block state and block model files don't really say anything about this. That's all hardcoded in Minecraft. In order for MiEx to know how to handle various kinds of blocks, you need to tell it to. This is done in the `miex_config.json` file. It has a few lists for different kinds of occluding, like transparent blocks and leaves blocks.

The default miex_config.json file has the vanilla leaves blocks added to the `leavesOcclusion` list, but not any of the modded leave blocks. So, these modded blocks need to be added to the right lists so that MiEx knows how to properly handle them. You can read more about the miex_config.json file and the various lists here: https://github.com/BramStoutProductions/MiEx/wiki/3.-Pipeline-Integration-and-Customisations#configurations

**Comment by BramStout** [comment]
The example `miex_config.json` file that I put in this post, shows some of the leaves blocks added to the `leavesOcclusion` list: https://github.com/BramStoutProductions/MiEx/issues/35#issuecomment-2081631048
