### ISSUE TITLE
Only solid colours

### ISSUE THREAD

**Issue by ExxorEX** [BramStoutProductions/MiEx#45]
Maya is exporting the textures with completely solid colours, i dunno if this is something im doing wrong since ive never used usd before. 
![image](https://github.com/BramStoutProductions/MiEx/assets/122947446/e305718d-f0d4-4b66-8918-990903e8a961)

**Comment by BramStout** [comment]
In the default material template of MiEx, it uses MaterialX for the materials. MaterialX comes with USD by default, but unfortunately not all applications support MaterialX materials when importing. Maya's USD importer doesn't really know how to handle MaterialX materials right now, and so it gives you just these preview colours.

I'll try to see if I can add a resource pack into the next release of MiEx that has material templates that Maya's USD importer can fully import, so that the textures will show up in Maya
