### ISSUE TITLE
Wrong Resource Pack Layering

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#61]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/b93ed807-cd20-460f-9f13-15b96eecf516)
The whole sculk thing looks blue with Faithless resource pack, but only inside should be white and inside is blue.
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/7307e84c-9b2a-4142-93d2-244d4a95f526)
Theres one duplicate object with the white version so yea, some kind of weird exporting glitch is there, is it possible to fix?

**Comment by BramStout** [comment]
The resource pack is able to make the inside blue and the outside white, because it's actually two cubes, one blue and one white. But, the blue cube has its normals facing inwards, while the white cube has its normals facing outwards. This works, because Minecraft renders out blocks with backface culling, so the blue cube is only visible on the inside and the white cube is only visible on the outside.

There was a small difference between how MiEx and Minecraft handle block models, that caused the blue cubes normals to not face inwards, but that has been fixed in the latest version.

So, MiEx and the Faithless resource pack both work correctly. The issue here is Blender not rendering the meshes with backface culling. This is actually the same issue as your other post https://github.com/BramStoutProductions/MiEx/issues/59

You can fix this by turning on Backface culling in the material settings. I'll check in with BlueEvilGFX to see if we can automate this in the Blender Addon
