### ISSUE TITLE
World won't export

### ISSUE THREAD

**Issue by Lumine-A** [BramStoutProductions/MiEx#83]
i made this world and load it into MiEx, and when it was about to export it gave me this error
![image](https://github.com/BramStoutProductions/MiEx/assets/168022830/199d7d58-b704-4b24-8f61-24afed057c21)
here is the log
[log.txt](https://github.com/user-attachments/files/15624891/log.txt)

**Comment by BramStout** [comment]
According to the log, you are using the 32 bit version of Java. This is fine for small exports, but for anything somewhat larger you'll run out of memory since the 32 bit version of Java can only use 4GB max, which is what's happening in your case.

I recommend uninstalling the 32 bit version of Java and installing the 64 bit version. That should fix your issue
