### ISSUE TITLE
Black Nether Warts

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#84]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/bea0aa94-ec5a-4b39-8c2c-ebd5e486ff32)
Whats up with that Bram?

**Comment by Fyoncle** [comment]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/d625a93d-f3e7-49a9-87ec-ddcce46628ee)
No matter how bright light, some places stay pitch black.

**Comment by Fyoncle** [comment]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/e9a4a194-90f0-4a4b-917a-4104b2e6ec04)
Same goes for the fires and stuff too.

**Comment by BramStout** [comment]
Minecraft renders out geometry as single sided (a.k.a. with backface culling). So in order to have something be able to be seen from both sides, you need to faces pointing in opposite directions. Since MiEx uses the same block models as Minecraft, it also behaves in the same way. This means that with the blocks that you're pointing out, you have two faces right on top of each other pointing in different directions. It could be that these are then casting shadows on each other making them appear black.

You should be able to fix it by increasing the geometry offset setting https://docs.blender.org/manual/en/latest/render/cycles/object_settings/object_data.html#shadow-terminator 

You could also add these block names to the `doubleSided` setting in the `miex_config.json` file ([wiki](https://github.com/BramStoutProductions/MiEx/wiki/4.-Resource-Packs#miex_configjson)), which will then tell MiEx to only export a single face rather than two

**Comment by Fyoncle** [comment]
> Minecraft renders out geometry as single sided (a.k.a. with backface culling). So in order to have something be able to be seen from both sides, you need to faces pointing in opposite directions. Since MiEx uses the same block models as Minecraft, it also behaves in the same way. This means that with the blocks that you're pointing out, you have two faces right on top of each other pointing in different directions. It could be that these are then casting shadows on each other making them appear black.
> 
> You should be able to fix it by increasing the geometry offset setting https://docs.blender.org/manual/en/latest/render/cycles/object_settings/object_data.html#shadow-terminator
> 
> You could also add these block names to the `doubleSided` setting in the `miex_config.json` file ([wiki](https://github.com/BramStoutProductions/MiEx/wiki/4.-Resource-Packs#miex_configjson)), which will then tell MiEx to only export a single face rather than two

Theres no 2 faces inside each other at all, and why Mineways doesn't have this glitch? this also goes for Glowberrys, Soulfires, Netherwarts and more.

**Comment by BramStout** [comment]
> > Minecraft renders out geometry as single sided (a.k.a. with backface culling). So in order to have something be able to be seen from both sides, you need to faces pointing in opposite directions. Since MiEx uses the same block models as Minecraft, it also behaves in the same way. This means that with the blocks that you're pointing out, you have two faces right on top of each other pointing in different directions. It could be that these are then casting shadows on each other making them appear black.
> > You should be able to fix it by increasing the geometry offset setting https://docs.blender.org/manual/en/latest/render/cycles/object_settings/object_data.html#shadow-terminator
> > You could also add these block names to the `doubleSided` setting in the `miex_config.json` file ([wiki](https://github.com/BramStoutProductions/MiEx/wiki/4.-Resource-Packs#miex_configjson)), which will then tell MiEx to only export a single face rather than two
> 
> Theres no 2 faces inside each other at all, and why Mineways doesn't have this glitch? this also goes for Glowberrys, Soulfires, Netherwarts and more.

There should be 2 faces inside each other, but since the vertices are merged you can't move them apart. If you try to delete a single face, you should see that the other one is still there.

The issue here is Cycles not handling this well, which is why it has the geometry offset setting. So increasing that should fix it. Mineways probably doesn't have this glitch because it doesn't fully copy how Minecraft does things, MiEx does and since Minecraft uses two faces, so does MiEx. If you don't want MiEx to put in two faces and instead just one, then add the block names to the `doubleSided` setting in the `miex_config.json` file.

**Comment by Fyoncle** [comment]
> > > Minecraft renders out geometry as single sided (a.k.a. with backface culling). So in order to have something be able to be seen from both sides, you need to faces pointing in opposite directions. Since MiEx uses the same block models as Minecraft, it also behaves in the same way. This means that with the blocks that you're pointing out, you have two faces right on top of each other pointing in different directions. It could be that these are then casting shadows on each other making them appear black.
> > > You should be able to fix it by increasing the geometry offset setting https://docs.blender.org/manual/en/latest/render/cycles/object_settings/object_data.html#shadow-terminator
> > > You could also add these block names to the `doubleSided` setting in the `miex_config.json` file ([wiki](https://github.com/BramStoutProductions/MiEx/wiki/4.-Resource-Packs#miex_configjson)), which will then tell MiEx to only export a single face rather than two
> > 
> > 
> > Theres no 2 faces inside each other at all, and why Mineways doesn't have this glitch? this also goes for Glowberrys, Soulfires, Netherwarts and more.
> 
> There should be 2 faces inside each other, but since the vertices are merged you can't move them apart. If you try to delete a single face, you should see that the other one is still there.
> 
> The issue here is Cycles not handling this well, which is why it has the geometry offset setting. So increasing that should fix it. Mineways probably doesn't have this glitch because it doesn't fully copy how Minecraft does things, MiEx does and since Minecraft uses two faces, so does MiEx. If you don't want MiEx to put in two faces and instead just one, then add the block names to the `doubleSided` setting in the `miex_config.json` file.

Why i have to add a config to EVERYTHING for making MiEx work as normal? Thats not fair :(

**Comment by BramStout** [comment]
> > > > Minecraft renders out geometry as single sided (a.k.a. with backface culling). So in order to have something be able to be seen from both sides, you need to faces pointing in opposite directions. Since MiEx uses the same block models as Minecraft, it also behaves in the same way. This means that with the blocks that you're pointing out, you have two faces right on top of each other pointing in different directions. It could be that these are then casting shadows on each other making them appear black.
> > > > You should be able to fix it by increasing the geometry offset setting https://docs.blender.org/manual/en/latest/render/cycles/object_settings/object_data.html#shadow-terminator
> > > > You could also add these block names to the `doubleSided` setting in the `miex_config.json` file ([wiki](https://github.com/BramStoutProductions/MiEx/wiki/4.-Resource-Packs#miex_configjson)), which will then tell MiEx to only export a single face rather than two
> > > 
> > > 
> > > Theres no 2 faces inside each other at all, and why Mineways doesn't have this glitch? this also goes for Glowberrys, Soulfires, Netherwarts and more.
> > 
> > 
> > There should be 2 faces inside each other, but since the vertices are merged you can't move them apart. If you try to delete a single face, you should see that the other one is still there.
> > The issue here is Cycles not handling this well, which is why it has the geometry offset setting. So increasing that should fix it. Mineways probably doesn't have this glitch because it doesn't fully copy how Minecraft does things, MiEx does and since Minecraft uses two faces, so does MiEx. If you don't want MiEx to put in two faces and instead just one, then add the block names to the `doubleSided` setting in the `miex_config.json` file.
> 
> Why i have to add a config to EVERYTHING for making MiEx work as normal? Thats not fair :(

MiEx already works as normal. Autodesk Maya, Arnold, Renderman, and Redshift all handle this without any issue. It's just Cycles that apparently requires things to be done differently. Every software handles things differently, and so it's just not possible for MiEx to be able to handle everything perfectly for every piece of software, while also making sure everything looks exactly to how it looks in Minecraft.

So, the focus with MiEx is on being as close to Minecraft as possible. When you end up with a piece of software that behaves differently, then you have the config files that allow you to tell MiEx to behave differently so that it works well with your software. The whole point of all of these config files and resource packs is so that you can customise MiEx to be exactly what you need, just like everybody else can customise MiEx to exactly what they need. It does mean that you'll end up having to create config files and custom resource packs, but there isn't any other option.

**Comment by BramStout** [comment]
MiEx now has a new Blender addon that should fix this issue. Would you be able to try it and see if the issue this exists?

You can read more about the new Blender addon here: https://github.com/BramStoutProductions/MiEx/wiki/8.-Importing-into-DCCs#blender
