### ISSUE TITLE
[Suggestions] Combined Textures Export

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#85]
Just like in Mineways it would be great to have all the textures exported into 1 big image and not hundreds of materials.

## Why it should be added?
- Can improve performance
- Can be time saving from not applying same changes for hundreds of materials
- Can be more practical

## Why it shouldn't be added?
- Mod support can be a pain to implement into this system

Not sure if what i want is getting done by the thing called "Atleases" or however its typed, but no idea what that is, just wanted to open a suggestion just in case if Atleases not what i want.

**Comment by BramStout** [comment]
The name for such a big image with all of the textures is an atlas and it is in MiEx. You can use the [Atlas Creator Tool](https://github.com/BramStoutProductions/MiEx/wiki/4.-Resource-Packs#atlas-creator-tool) in MiEx to have it make the big images. It doesn't export it out into a single large image, but rather a few images based on what works best regarding materials.

The Atlas Creator Tool also works with modded resource packs, connected textures, and PBR textures. When running the tool, do make sure to enable all resource packs that you would normally have enabled during the export. Then the tool can combine the various textures from all of them and combine them into the same atlases. Also include the resource packs that provide the material templates that you want to use, since that affects how it categorises the textures into the different atlases. And you can specify the name of the resource pack that it should export the atlases into. This can be any name and if there isn't a resource pack with that name, it'll create it for you. This allows you to have the atlases in a separate resource pack, so that you can easily toggle atlases on and off by enabling or disabling the resource pack.
