### ISSUE TITLE
Chunk Not Supported

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#86]
When will chunk support come for the older worlds?

**Comment by BramStout** [comment]
The upcoming main version of MiEx is focusing on support for Bedrock Edition. The main version after that will focus on support for older worlds.

**Comment by Fyoncle** [comment]
> The upcoming main version of MiEx is focusing on support for Bedrock Edition. The main version after that will focus on support for older worlds.

Is MiEx supports 1.8 worlds that is "new"?

**Comment by BramStout** [comment]
> > The upcoming main version of MiEx is focusing on support for Bedrock Edition. The main version after that will focus on support for older worlds.
> 
> Is MiEx supports 1.8 worlds that is "new"?

MiEx currently supports worlds from Minecraft 21w43a and later. MiEx 1.8.X (1.7.X will have the Bedrock support) will have support for older versions of Minecraft, but I can't say how far back the supported versions of Minecraft it'll go. Hopefully Minecraft 1.13 and later should then get support, but for older versions it'll be a bit tricky. That's because they [changed up a lot of stuff regarding block names and block states](https://minecraft.wiki/w/Java_Edition_1.13/Flattening) so it would require translating the world from versions before 1.13 to after 1.13.

Fortunately, with the support for Bedrock Edition comes such a translation framework. MiEx will actually translate Bedrock Edition worlds into Java Edition which would allow you to use Java Edition resource packs with Bedrock Edition worlds and vice versa. This same system could then also be used to translate Java 1.12 and lower to Java 1.13 and later, but that would still be a lot of work.
